### ISSUE TITLE
【735-week 01】学习总结

### ISSUE THREAD

**Issue by fuchenxi** [algorithm004-05/algorithm004-05#236]
感觉本周学习对自己收获最大的就是双指针, 仿佛打开了新世界的大门. 对于解题不能局限于暴力循环遍历的方式上, 需要多学习LeetCode上那些较好的解题思路. 都说算法实际工作中应用不到, 殊不知很多时候都是用两层甚至三层嵌套for循环去实现一些功能(手动羞涩…).

我觉得学习算法本身, 其实就是训练自己的思维, 遇到问题尝试不同的方式去求解, 从而比较出一个最优解. 

不足: 五毒神掌没有领悟其精髓, 还需努力修炼.

**Comment by quzhen12** [comment]
让我收获最大的就是学习方式和思维，一种是如何去学，一种是如何思考

**Comment by stormlzw** [comment]
都是循环实现，但是双指针的用法真的是打开了自己眼界
